stages:
  model_selection:
    cmd: python3 2_model_selection.py
    deps:
    - 2_model_selection.py
    - configs/config.yaml
    - data/train.csv
    - data/y_train.csv
    outs:
    - model_selection_results.yaml
    - mlruns/
  preprocess:
    cmd: python 1_preprocessing.py
    deps:
    - 1_preprocessing.py
    - configs/config.yaml
    - data/data.csv
    outs:
    - data/cleaned_data.csv
    - data/preprocessing_pipeline.pkl
    - data/test.csv
    - data/train.csv
    - data/y_test.csv
    - data/y_train.csv
  hyperparameter_tuning:
    cmd: python3 3_hyperparameter_tuning.py
    deps:
    - 3_hyperparameter_tuning.py
    - configs/config.yaml
    - data/test.csv
    - data/train.csv
    - data/y_test.csv
    - data/y_train.csv
    - model_selection_results.yaml
    - mlruns/
    outs:
    - tuning_results.yaml
  train:
    cmd: python3 4_train.py
    deps:
    - 4_train.py
    - configs/config.yaml
    - data/test.csv
    - data/train.csv
    - data/y_test.csv
    - data/y_train.csv
    - mlruns/
    outs:
    - trained_models/final_model.pkl
    - trained_models/final_model_results.yaml
