# @package _global_.preprocessing
_target_: preprocessing.complex_preprocessing_pipeline

# Features to drop from the dataset
features_to_drop:
  - customerID

# Features to impute (numerical features with missing values)
features_to_impute:
  - TotalCharges

# Imputation method: 'mean' or 'median'
imputation_method: median

# Features to encode (categorical features) - using OrdinalEncoder
features_to_encode:
  - gender
  - Partner
  - Dependents
  - PhoneService
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod

# Features to scale (numerical features)
features_to_scale:
  - tenure
  - MonthlyCharges
  - TotalCharges
