name: logistic_regression
model: sklearn.linear_model.LogisticRegression
params:
  penalty: l2
  fit_intercept: true
  random_state: 42
  n_jobs: -1

param_grid:
  penalty: [l2, l1, elasticnet]
  fit_intercept: [true, false]