# Main configuration file
defaults:
  - preprocessing: simple_preprocessor
  - _self_

# Hydra output directory configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false
