defaults:
  - model: logistic_regression
  - tuning: grid
  - _self_
  
data:
  data_path: data/data.csv
  cleaned_data_path: data/cleaned_data.csv
  train_path: data/train.csv
  test_path: data/test.csv
  y_train_path: data/y_train.csv
  y_test_path: data/y_test.csv
  preprocessing_pipeline_path: data/preprocessing_pipeline.pkl
  test_size: 0.2
  random_state: 42
  
selection:
  cv_folds: 5
  scoring: roc_auc
  models:
    - logistic_regression
    - svm
    - knn
    - random_forest
  
tuning:
  cv_folds: 5
  n_jobs: -1
  scoring: roc_auc

mlflow:
  experiment_name: model_development
  tracking_uri: mlruns