# MLflow tracking configuration
mlflow:
  # Tracking URI (default: local mlruns directory)
  tracking_uri: ./mlruns

  # Experiment names
  experiment_name: telco-churn-experiments

  # Run configuration
  run_name: null  # Will be set automatically if null

  # Autolog settings
  autolog:
    enabled: false
    log_models: true
    log_input_examples: false
    log_model_signatures: true
